# Generated by Django 3.2.15 on 2022-09-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220915_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.base'),
        ),
        migrations.AlterField(
            model_name='polloptions',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollOpts', to='backend.base'),
        ),
    ]
