# Generated by Django 3.2.15 on 2022-09-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220915_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='kids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.comment'),
        ),
        migrations.AlterField(
            model_name='polloptions',
            name='kids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.polloptions'),
        ),
    ]
