# Generated by Django 3.2.15 on 2022-09-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220915_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polloptions',
            options={'verbose_name_plural': 'Poll Options'},
        ),
        migrations.AlterField(
            model_name='base',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='polloptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
