# Generated by Django 3.2.15 on 2022-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220915_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
